# Generated by Django 3.0.3 on 2020-03-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['image_title']},
        ),
        migrations.AddField(
            model_name='image',
            name='image_category',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_title',
            field=models.CharField(max_length=60),
        ),
    ]
