# Generated by Django 3.0.3 on 2020-03-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='image_location',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
