# Generated by Django 3.0.3 on 2020-03-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20200302_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_url',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
